# Generated by Django 5.2 on 2025-05-21 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleado', '0001_initial'),
        ('Espacio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaisajeSonoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField()),
                ('duracion', models.DurationField()),
                ('descripcion', models.TextField(blank=True)),
                ('artista', models.ForeignKey(limit_choices_to={'tipo_empleado': 'Artista Sonoro'}, on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado')),
                ('espacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Espacio.espacio')),
            ],
        ),
    ]
