# Generated by Django 5.2 on 2025-05-22 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleado', '0001_initial'),
        ('Paisaje_sonoro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paisajesonoro',
            name='artista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.empleado'),
        ),
    ]
