# Generated by Django 5.2 on 2025-05-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paisaje_sonoro', '0002_alter_paisajesonoro_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paisajesonoro',
            name='duracion',
            field=models.CharField(max_length=10),
        ),
    ]
